@host=http://192.168.1.17:3000/user/reset-password
GET {{host}}
Content-Type: application/json

{
   
}

### POST Request
POST {{host}}
Content-Type: application/json

{
   "madocgia": "DG0639",  // Mã độc giả, lấy từ nơi bạn đã xác định
    "ngaymuon": null,
    "masachList": ["1","2"] // Danh
}

### PUT Request
PUT {{host}}
Content-Type: application/json

{
   "maphieumuon":"1",
   "ghichu":"s",
    "masachList":[""]
}

### delete Request
DELETE  {{host}}

Content-Type: application/json
{
}

